import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# ============================================================
# 1. Load cleaned transaction data
# ============================================================

df = pd.read_csv("data/cleaned/retail_clean.csv")

# Convert InvoiceDate from text to datetime format
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print("Rows loaded:", len(df))
print("First date:", df["InvoiceDate"].min())
print("Last date:", df["InvoiceDate"].max())


# ============================================================
# 2. Basic dataset inspection
# ============================================================

print("\nFirst 5 rows:")
print(df.head())

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData types:")
print(df.dtypes)


# ============================================================
# 3. Missing values and duplicates
# ============================================================

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())


# ============================================================
# 4. Numerical summary
# ============================================================

print("\nNumerical summary:")
print(df.describe())

print("\nRevenue statistics:")
print(df["Revenue"].describe())


# ============================================================
# 5. Revenue distribution
# ============================================================

plt.figure(figsize=(8, 5))

sns.histplot(
    df["Revenue"],
    bins=50
)

plt.title("Revenue Distribution")
plt.xlabel("Revenue")
plt.ylabel("Number of Transactions")

plt.tight_layout()
plt.show()


# ============================================================
# 6. Monthly revenue
# ============================================================
# Groups transactions by month and calculates total revenue.

monthly_revenue = (
    df.groupby(
        df["InvoiceDate"].dt.to_period("M")
    )["Revenue"]
    .sum()
    .reset_index()
)

print("\nMonthly revenue:")
print(monthly_revenue)

print("\nNumber of months:")
print(len(monthly_revenue))


# ============================================================
# 7. Monthly revenue trend
# ============================================================

plt.figure(figsize=(12, 5))

plt.plot(
    monthly_revenue["InvoiceDate"].astype(str),
    monthly_revenue["Revenue"]
)

plt.title("Monthly Revenue")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()


# ============================================================
# 8. Customer revenue analysis
# ============================================================
# Calculate total revenue generated by each customer.

customer_revenue = (
    df.groupby("CustomerID")["Revenue"]
      .sum()
      .sort_values(ascending=False)
)

print("\nTop 10 customers by revenue:")
print(customer_revenue.head(10))


# ============================================================
# 9. Top 10 customers visualization
# ============================================================

top_customers = customer_revenue.head(10)

plt.figure(figsize=(10, 5))

top_customers.sort_values().plot(
    kind="barh"
)

plt.title("Top 10 Customers by Revenue")
plt.xlabel("Revenue")
plt.ylabel("Customer ID")

plt.tight_layout()
plt.show()

#--------------------------------
#cohort heatmap
# ------------------------------------------------------------

# Load cohort retention data
cohort = pd.read_csv("data/cleaned/cohort_retention.csv")

# Convert cohort month to a readable string
cohort["cohort_month"] = pd.to_datetime(
    cohort["cohort_month"]
).dt.strftime("%Y-%m")

# Convert long format into a matrix:
# rows = cohort months
# columns = months since first purchase
# values = retention %
cohort_pivot = cohort.pivot(
    index="cohort_month",
    columns="cohort_month_number",
    values="retention_pct"
)

print("\nCohort retention matrix:")
print(cohort_pivot)

# Create heatmap
plt.figure(figsize=(14, 8))

sns.heatmap(
    cohort_pivot,
    annot=True,
    fmt=".1f",
    cmap="Blues",
    linewidths=0.5
)

plt.title("Customer Cohort Retention")
plt.xlabel("Months Since First Purchase")
plt.ylabel("Cohort Month")

plt.tight_layout()
plt.show()