-- ============================================================
-- PHASE 3: RFM CUSTOMER SEGMENTATION IN SQL
-- ============================================================
-- RFM stands for:
-- R = Recency    -> How recently the customer purchased
-- F = Frequency  -> How often the customer purchased
-- M = Monetary   -> How much revenue the customer generated
--
-- Goal:
-- Segment customers based on their purchasing behaviour.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Check existing customer summary
-- ------------------------------------------------------------

SELECT *
FROM customer_summary
LIMIT 10;


-- ------------------------------------------------------------
-- 2. Find the analysis end date
-- ------------------------------------------------------------
-- The latest transaction date is used as the reference date
-- for calculating customer recency.

SELECT MAX(InvoiceDate) AS analysis_end_date
FROM retail_clean;


-- ------------------------------------------------------------
-- 3. Calculate raw RFM metrics
-- ------------------------------------------------------------
-- Recency:
-- Number of days since the customer's most recent purchase.
--
-- Frequency:
-- Number of distinct orders/invoices made by the customer.
--
-- Monetary:
-- Total revenue generated by the customer.
--
-- Each row represents one customer.

SELECT
    CustomerID,

    -- Number of days since the customer's last purchase
    DATEDIFF(
        (SELECT DATE(MAX(InvoiceDate)) FROM retail_clean),
        DATE(MAX(InvoiceDate))
    ) AS recency,

    -- Number of distinct orders
    COUNT(DISTINCT Invoice) AS frequency,

    -- Total customer revenue
    ROUND(SUM(Revenue), 2) AS monetary

FROM retail_clean
GROUP BY CustomerID;


-- ------------------------------------------------------------
-- 4. Store the raw RFM metrics
-- ------------------------------------------------------------
-- Creates a reusable table containing one row per customer
-- with their Recency, Frequency and Monetary values.

CREATE TABLE customer_rfm_raw AS
SELECT
    CustomerID,

    DATEDIFF(
        (SELECT DATE(MAX(InvoiceDate)) FROM retail_clean),
        DATE(MAX(InvoiceDate))
    ) AS recency,

    COUNT(DISTINCT Invoice) AS frequency,

    ROUND(SUM(Revenue), 2) AS monetary

FROM retail_clean
GROUP BY CustomerID;


-- Preview the RFM table
SELECT *
FROM customer_rfm_raw
LIMIT 10;


-- Check total number of customers in the RFM table
SELECT COUNT(*) AS customers
FROM customer_rfm_raw;


-- Compare with the existing customer summary
SELECT COUNT(*)
FROM customer_summary;


-- ------------------------------------------------------------
-- 5. Test Frequency scoring using NTILE
-- ------------------------------------------------------------
-- NTILE(5) divides customers into 5 approximately equal groups.
--
-- Frequency is ordered in ascending order:
-- 1 = lowest frequency
-- 5 = highest frequency

SELECT
    CustomerID,
    frequency,
    NTILE(5) OVER (
        ORDER BY frequency
    ) AS frequency_score
FROM customer_rfm_raw;


-- ------------------------------------------------------------
-- 6. Test Monetary scoring using NTILE
-- ------------------------------------------------------------
-- Monetary is ordered in ascending order:
-- 1 = lowest monetary value
-- 5 = highest monetary value

SELECT
    CustomerID,
    monetary,
    NTILE(5) OVER (
        ORDER BY monetary
    ) AS monetary_score
FROM customer_rfm_raw;


-- ------------------------------------------------------------
-- 7. Create RFM scores
-- ------------------------------------------------------------
-- Each RFM metric is converted into a score from 1 to 5.
--
-- Recency is ordered DESC because:
-- Lower recency days = more recent purchase = better score.
--
-- Frequency and Monetary are ordered ASC because:
-- Higher frequency/monetary value = better score.

CREATE TABLE customer_rfm_scored AS
SELECT
    CustomerID,
    recency,
    frequency,
    monetary,

    -- More recent customers receive higher scores
    NTILE(5) OVER (
        ORDER BY recency DESC
    ) AS recency_score,

    -- More frequent customers receive higher scores
    NTILE(5) OVER (
        ORDER BY frequency
    ) AS frequency_score,

    -- Higher-spending customers receive higher scores
    NTILE(5) OVER (
        ORDER BY monetary
    ) AS monetary_score

FROM customer_rfm_raw;


-- Preview scored RFM data
SELECT *
FROM customer_rfm_scored
LIMIT 10;


-- ------------------------------------------------------------
-- 8. Create RFM code and total score
-- ------------------------------------------------------------
-- RFM score:
-- Combines the three individual scores into one code.
--
-- Example:
-- 555 = high Recency + high Frequency + high Monetary
-- 151 = high Recency + low Frequency + high Monetary
--
-- RFM total:
-- Adds the three scores together.
-- Minimum possible score = 3
-- Maximum possible score = 15

SELECT
    CustomerID,
    recency,
    frequency,
    monetary,
    recency_score,
    frequency_score,
    monetary_score,

    CONCAT(
        recency_score,
        frequency_score,
        monetary_score
    ) AS rfm_score,

    recency_score
        + frequency_score
        + monetary_score AS rfm_total

FROM customer_rfm_scored
LIMIT 20;


-- ------------------------------------------------------------
-- 9. Create customer segments
-- ------------------------------------------------------------
-- Segment customers using their RFM scores.
--
-- Champions:
-- High Recency + High Frequency + High Monetary
--
-- Loyal:
-- High Frequency
--
-- At Risk:
-- Low Recency, but reasonable Frequency or Monetary value
--
-- Lost:
-- Low Recency + Low Frequency + Low Monetary
--
-- Other:
-- Customers who do not fall into the above categories.

CREATE TABLE customer_segments AS
SELECT
    CustomerID,
    recency,
    frequency,
    monetary,
    recency_score,
    frequency_score,
    monetary_score,

    -- Combine individual RFM scores
    CONCAT(
        recency_score,
        frequency_score,
        monetary_score
    ) AS rfm_score,

    -- Calculate total RFM score
    recency_score
        + frequency_score
        + monetary_score AS rfm_total,

    -- Assign customer segment based on RFM behaviour
    CASE
        WHEN recency_score >= 4
             AND frequency_score >= 4
             AND monetary_score >= 4
            THEN 'Champions'

        WHEN frequency_score >= 4
            THEN 'Loyal'

        WHEN recency_score <= 2
             AND (
                 frequency_score >= 3
                 OR monetary_score >= 3
             )
            THEN 'At Risk'

        WHEN recency_score <= 2
             AND frequency_score <= 2
             AND monetary_score <= 2
            THEN 'Lost'

        ELSE 'Other'
    END AS segment

FROM customer_rfm_scored;


-- ------------------------------------------------------------
-- 10. Revenue and customer count by segment
-- ------------------------------------------------------------
-- Shows how many customers are in each segment and the
-- historical revenue generated by each segment.

SELECT
    segment,
    COUNT(*) AS customers,
    ROUND(SUM(monetary), 2) AS revenue
FROM customer_segments
GROUP BY segment
ORDER BY customers DESC;


-- ------------------------------------------------------------
-- 11. Customer and revenue percentage by segment
-- ------------------------------------------------------------
-- Customer percentage:
-- Percentage of total customers in each segment.
--
-- Revenue percentage:
-- Percentage of total historical revenue generated
-- by each segment.

SELECT
    segment,
    COUNT(*) AS customers,

    ROUND(
        COUNT(*) /
        (SELECT COUNT(*) FROM customer_segments) * 100,
        2
    ) AS customer_percentage,

    ROUND(SUM(monetary), 2) AS revenue,

    ROUND(
        SUM(monetary) /
        (SELECT SUM(monetary) FROM customer_segments) * 100,
        2
    ) AS revenue_percentage

FROM customer_segments
GROUP BY segment
ORDER BY revenue DESC;


-- ------------------------------------------------------------
-- 12. Average customer behaviour by segment
-- ------------------------------------------------------------
-- Compare the average Recency, Frequency and Monetary
-- values across customer segments.

SELECT
    segment,

    COUNT(*) AS customers,

    ROUND(AVG(recency), 1) AS avg_recency_days,

    ROUND(AVG(frequency), 2) AS avg_orders,

    ROUND(AVG(monetary), 2) AS avg_customer_revenue

FROM customer_segments
GROUP BY segment
ORDER BY avg_customer_revenue DESC;


-- ------------------------------------------------------------
-- 13. Inspect top Champions
-- ------------------------------------------------------------
-- Shows the highest-value customers classified as Champions.

SELECT
    CustomerID,
    recency,
    frequency,
    monetary,
    rfm_score,
    rfm_total
FROM customer_segments
WHERE segment = 'Champions'
ORDER BY monetary DESC
LIMIT 20;


-- ------------------------------------------------------------
-- 14. Inspect high-value At Risk customers
-- ------------------------------------------------------------
-- These customers have become less recent but may still
-- have meaningful historical value.
-- They can be potential targets for retention campaigns.

SELECT
    CustomerID,
    recency,
    frequency,
    monetary,
    rfm_score,
    rfm_total
FROM customer_segments
WHERE segment = 'At Risk'
ORDER BY monetary DESC
LIMIT 20;


-- ------------------------------------------------------------
-- 15. Historical revenue by segment
-- ------------------------------------------------------------
-- Shows the total historical revenue contributed by
-- each customer segment.

SELECT
    segment,
    ROUND(SUM(monetary), 2) AS historical_revenue,
    COUNT(*) AS customers
FROM customer_segments
GROUP BY segment
ORDER BY historical_revenue DESC;


-- ------------------------------------------------------------
-- 16. Recency score distribution
-- ------------------------------------------------------------
-- Shows how many customers received each Recency score.

SELECT
    recency_score,
    COUNT(*) AS customers
FROM customer_segments
GROUP BY recency_score
ORDER BY recency_score;


-- ------------------------------------------------------------
-- 17. Frequency score distribution
-- ------------------------------------------------------------
-- Shows how many customers received each Frequency score.

SELECT
    frequency_score,
    COUNT(*) AS customers
FROM customer_segments
GROUP BY frequency_score
ORDER BY frequency_score;


-- ------------------------------------------------------------
-- 18. Monetary score distribution
-- ------------------------------------------------------------
-- Shows how many customers received each Monetary score.

SELECT
    monetary_score,
    COUNT(*) AS customers
FROM customer_segments
GROUP BY monetary_score
ORDER BY monetary_score;


-- ------------------------------------------------------------
-- 19. Create segment summary table
-- ------------------------------------------------------------
-- Creates a compact summary table for each customer segment.
-- This table can later be used for analysis or Power BI.

CREATE TABLE segment_summary AS
SELECT
    segment,
    COUNT(*) AS customers,
    ROUND(SUM(monetary), 2) AS revenue,
    ROUND(AVG(recency), 2) AS avg_recency,
    ROUND(AVG(frequency), 2) AS avg_frequency,
    ROUND(AVG(monetary), 2) AS avg_monetary
FROM customer_segments
GROUP BY segment;


-- View segment summary
SELECT *
FROM segment_summary
ORDER BY revenue DESC;


-- ------------------------------------------------------------
-- 20. Validate customer counts
-- ------------------------------------------------------------
-- Checks whether every row represents a unique customer.
--
-- total_customers and unique_customers should match.

SELECT
    COUNT(*) AS total_customers,
    COUNT(DISTINCT CustomerID) AS unique_customers
FROM customer_segments;


-- ------------------------------------------------------------
-- 21. Check for missing segment assignments
-- ------------------------------------------------------------
-- Ensures that no customer has a NULL segment.

SELECT *
FROM customer_segments
WHERE segment IS NULL;


-- ============================================================
-- END OF PHASE 3: RFM CUSTOMER SEGMENTATION
-- ============================================================